name: C++ CI with Google Test

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS to run the tests on (Ubuntu in this case)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out your code

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: g++  # Set up the C++ compiler

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make libgtest-dev

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./your_test_executable_name  # Replace with your test executable
